name: Generates changelog

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The version of the new release
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install tools
        run: pip install foxy-project
      - name: Identificate github bot
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Create new branch
        run: git switch -c "version/${{ github.event.inputs.inputs.version }}"
      - name: Generate the new changelog
        run: foxy-project changelog -v ${{ github.event.inputs.inputs.version }}
      - name: Commit & push
        run: |
          git add .
          git commit -m "version(${{ github.event.inputs.inputs.version }}): generate changelog"
          git push origin "version/${{ github.event.inputs.inputs.version }}"
      - name: Create pull request
        run: |
          gh pr create --fill-first
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
